/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zero.movies;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Benavides
 */
public class administradorPel extends javax.swing.JFrame {

    
    /**
     * Creates new form administradorPel
     */
        Listapelicula lp=new Listapelicula();
        File peliculas= new File ("peliculas.txt");
    public administradorPel() {
        
        initComponents();
        setLocationRelativeTo(null);
        update();
        fullList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        consultBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Genero", "Duracion", "Imagen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        addBtn.setText("Agregar");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });

        deleteBtn.setText("Eliminar");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });

        consultBtn.setText("Consultar");
        consultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Modificar");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(addBtn)
                .addGap(63, 63, 63)
                .addComponent(deleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(consultBtn)
                .addGap(47, 47, 47)
                .addComponent(editBtn)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(deleteBtn)
                    .addComponent(consultBtn)
                    .addComponent(editBtn))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        // TODO add your handling code here:
        agregarPel ap= new agregarPel();
        ap.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_addBtnMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        int numfila= jTable1.getSelectedRow();
        if(numfila>=0){
            lp.delete(numfila);
            lp.consult();
            lp.erase();
            lp.writeinFile();
            this.update();
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un pelicula para eliminar");
        }
        
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void consultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultBtnActionPerformed
        // TODO add your handling code here:
        int numfila= jTable1.getSelectedRow();
        if(numfila>=0){
            consultarPel cP=new consultarPel();
            cP.numfila=jTable1.getSelectedRow();
            cP.lp=this.lp;
            cP.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un pelicula para consultar");
        }
    }//GEN-LAST:event_consultBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        int numfila=this.jTable1.getSelectedRow();
        if(numfila>=0){
            modificarPel mP=new modificarPel();
            mP.numfila=jTable1.getSelectedRow();
            mP.lp=this.lp;
            mP.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un pelicula para modificar");
        }
    }//GEN-LAST:event_editBtnActionPerformed
    
    public void update() {
        String linea;        
        Funcion f= new Funcion();
        
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        // borrando los datos que se encuentran en la tabla
        int modelsize=model.getRowCount();
        // 
        while(modelsize!=0 ){
            model.removeRow(0);
            modelsize--;
        }
        if(peliculas.exists()){
            try {
                FileReader fr1=new FileReader(peliculas);BufferedReader br1= new BufferedReader(fr1);
                if(br1.readLine().equals("#")){
                    if(modelsize==1){
                        model.removeRow(0);
                    }
                    
                    JOptionPane.showMessageDialog(null, "Lista de peliculas ");
                }else{
                    FileReader fr=new FileReader(peliculas);BufferedReader br= new BufferedReader(fr);
                    while((linea=br.readLine())!=null){
                        String nombre=f.dividir(linea, "#", 0);
                        String genero=f.dividir(linea, "#", 1);
                        String duracion=f.dividir(linea, "#", 2);
                        String imagen=f.dividir(linea, "#", 3);
                       
                        
                        Object[] fila={nombre,genero,duracion,imagen};
                        model.addRow(fila);
                    }
                    
                }
            } catch (FileNotFoundException ex) {
                
            } catch (IOException ex) {
                
            }   
        }else{
            JOptionPane.showMessageDialog(null, "no hay peliculas");
        }
        
    }
    
    public void fullList(){
        Funcion f= new Funcion();
        String linea;
        try{
            FileReader fr=new FileReader(peliculas);BufferedReader br= new BufferedReader(fr);
            
                    while((linea=br.readLine())!=null){
                        if("#".equals(linea) || linea==null){
                            System.out.println("archivo vacio");
                        }else{
                            String nombre=f.dividir(linea, "#", 0);
                            String genero=f.dividir(linea, "#", 1);
                            String dur=f.dividir(linea, "#", 2);
                            
                            int duracion=Integer.parseInt(dur);
                            String imagen=f.dividir(linea, "#", 3);
                            lp.add(new Nodopelicula(nombre,genero,imagen,duracion));
                        }    
                    }
            
        }catch(IOException e){
            
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administradorPel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administradorPel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administradorPel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administradorPel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administradorPel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton consultBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
